# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: anolivei <anolivei@student.42sp.org>       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/07/14 00:45:34 by anolivei          #+#    #+#              #
#    Updated: 2020/07/15 17:45:22 by anolivei         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

build:
	gcc *.c -lcurl -o student-search;

run:
	./student-search;

clean:
	rm student-search;
	rm data.txt;
